export const clients = [
  {
    id: "client-1",
    slug: "ms-recebiveis",
    name: "MS Recebíveis",
    segment: "Financeiro",
    status: "Ativo",
    owner: "Albert",
    serviceType: "Conteúdo + Estratégia",
    location: "Marabá, PA",
    activeDemands: 6,
    activeCampaigns: 2,
    summary: "Conta com foco em autoridade, conteúdo de mercado e posicionamento institucional.",
  },
  {
    id: "client-2",
    slug: "casa-galvani",
    name: "Casa Galvani",
    segment: "Varejo / Gastronomia",
    status: "Ativo",
    owner: "Albert",
    serviceType: "Social Media",
    location: "Rodovia, PA",
    activeDemands: 4,
    activeCampaigns: 1,
    summary: "Conta de presença digital com foco em storytelling, experiência e fluxo de visita.",
  },
  {
    id: "client-3",
    slug: "talisma-seguros",
    name: "Talismã Seguros",
    segment: "Seguros",
    status: "Ativo",
    owner: "Albert",
    serviceType: "Performance + Comercial",
    location: "PA",
    activeDemands: 7,
    activeCampaigns: 3,
    summary: "Conta mais densa em mídia, CRM, LP, ActiveCampaign e leitura de funil.",
  },
];

export const demands = [
  {
    id: "demand-1",
    slug: "carrossel-duplicata-escritural",
    name: "Carrossel duplicata escritural",
    client: "MS Recebíveis",
    clientSlug: "ms-recebiveis",
    type: "Conteúdo",
    priority: "Alta",
    status: "Em produção",
    owner: "Conteúdo",
    dueDate: "Hoje",
    description: "Fechar capa e sequência do carrossel institucional.",
    nextStep: "Validar arte final da capa e subir sequência visual.",
  },
  {
    id: "demand-2",
    slug: "stories-semana-casa-galvani",
    name: "Stories semanais Casa Galvani",
    client: "Casa Galvani",
    clientSlug: "casa-galvani",
    type: "Stories",
    priority: "Média",
    status: "Planejamento",
    owner: "Social",
    dueDate: "Amanhã",
    description: "Semana focada em café, queijo, vinho, doces e espetos.",
    nextStep: "Separar cenas ideais e organizar calendário de captação.",
  },
  {
    id: "demand-3",
    slug: "auditoria-meta-ac-talisma",
    name: "Auditoria Meta + AC Talismã",
    client: "Talismã Seguros",
    clientSlug: "talisma-seguros",
    type: "Performance",
    priority: "Alta",
    status: "Em andamento",
    owner: "Mídia",
    dueDate: "Sexta",
    description: "Leitura de campanhas, LP e ActiveCampaign.",
    nextStep: "Fechar checklist de UTM, GA e passagem para CRM.",
  },
  {
    id: "demand-4",
    slug: "estrutura-mvp-qconverte-os",
    name: "Estrutura MVP QConverte OS",
    client: "QConverte",
    clientSlug: "qconverte",
    type: "Produto",
    priority: "Alta",
    status: "Backlog",
    owner: "Produto",
    dueDate: "Próxima sprint",
    description: "Subir versão inicial clicável com dashboard, clientes, demandas e entregas.",
    nextStep: "Transformar v0 em v1 com mais sensação de sistema real.",
  },
];

export const deliveries = [
  {
    id: "delivery-1",
    name: "Capa post fixo MS",
    client: "MS Recebíveis",
    clientSlug: "ms-recebiveis",
    relatedDemand: "Carrossel duplicata escritural",
    demandSlug: "carrossel-duplicata-escritural",
    type: "Design",
    status: "Revisão interna",
    owner: "Design",
    dueDate: "Hoje",
    stage: "Layout",
  },
  {
    id: "delivery-2",
    name: "Roteiros stories Casa Galvani",
    client: "Casa Galvani",
    clientSlug: "casa-galvani",
    relatedDemand: "Stories semanais Casa Galvani",
    demandSlug: "stories-semana-casa-galvani",
    type: "Copy",
    status: "Concluído",
    owner: "Conteúdo",
    dueDate: "Hoje",
    stage: "Texto aprovado",
  },
  {
    id: "delivery-3",
    name: "Relatório leitura campanhas Talismã",
    client: "Talismã Seguros",
    clientSlug: "talisma-seguros",
    relatedDemand: "Auditoria Meta + AC Talismã",
    demandSlug: "auditoria-meta-ac-talisma",
    type: "Relatório",
    status: "Em produção",
    owner: "Performance",
    dueDate: "Sexta",
    stage: "Diagnóstico",
  },
];

export const recentActivity = [
  {
    id: "activity-1",
    title: "Nova leitura de campanhas da Talismã registrada",
    detail: "Meta + ActiveCampaign + LP mapeados com foco em funil.",
    time: "há 22 min",
  },
  {
    id: "activity-2",
    title: "Semana de stories da Casa Galvani estruturada",
    detail: "Foco em café, queijo, vinho, doces, churrasco e espetos.",
    time: "há 1 h",
  },
  {
    id: "activity-3",
    title: "MS Recebíveis com nova linha de posts de alcance",
    detail: "Pauta reposicionada para mais engajamento e conexão com dor real.",
    time: "há 2 h",
  },
];
